name: Create and Upload hello.txt to Artifactory

on:
  push:
    branches:
      - main   # Trigger the action on the 'main' branch (adjust as necessary)

jobs:
  upload_hello_file:
    runs-on: ubuntu-latest  # Use Ubuntu as the runner environment

    steps:
    
      # Step 2: Create hello.txt file with "Hello, World!" text
      - name: Create hello.txt file
        run: echo "Hello, World!" > hello.txt

      # Step 3: Set up JFrog CLI
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        with:
          version: '2.10.1'  # Use the latest version of JFrog CLI

      # Step 4: Configure JFrog CLI with Artifactory credentials
      - name: Configure JFrog CLI with Artifactory credentials
        run: |
          jf config add \
            --url ${{ secrets.ARTIFACTORY_URL }} \
            --user ${{ secrets.ARTIFACTORY_USER }} \
            --password ${{ secrets.ARTIFACTORY_API_KEY }} \
            --interactive=false

      # Step 5: Upload hello.txt to Artifactory
      - name: Upload hello.txt to Artifactory
        run: |
          jf rt u "hello.txt" "ramya-generic-local/hello-world/"

      # Step 6: Verify uploaded file in Artifactory (optional)
      - name: Verify uploaded file in Artifactory
        run: |
          jf rt s "ramya-generic-local/hello-world/hello.txt"
