
name: "Frogbot Scan Repository"
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  pull-requests: write
  contents: write
  security-events: write
  id-token: write
jobs:
  frogbot-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["main"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install npm dependencies
        run: npm install
      - uses: jfrog/frogbot@v3
        with:
          oidc-provider-name: ramya-frogbot
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_GIT_TOKEN: ${{ secrets.JF_GIT_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
          JFROG_CLI_LOG_LEVEL: DEBUG
          JF_FAIL: true
          JF_FIX_AND_PULL_REQUEST: "false"
          JF_USE_CONFIG_PROFILE: true
          JF_INCLUDE_ALL_VULNERABILITIES: true
