name: Upload Hello World to Artifactory

on:
  workflow_dispatch:  # Allows you to run it manually from the GitHub UI

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      # Checkout code (not strictly necessary here, but good practice)
      - name: Checkout code
        uses: actions/checkout@v2

      # Create hello.txt file
      - name: Create hello.txt
        run: echo "Hello, World!" > hello.txt

      # Set up JFrog CLI
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        with:
          version: '2.10.1'  # You can change to the latest version if needed

      # Configure JFrog CLI with Artifactory API key and Artifactory URL from GitHub Secrets
      - name: Configure JFrog CLI
        run: |
          jfrog rt config --url ${{ secrets.ARTIFACTORY_URL }} \
                          --apikey ${{ secrets.ARTIFACTORY_API_KEY }} \
                          --interactive=false

      # Upload the file to Artifactory
      - name: Upload hello.txt to Artifactory
        run: |
          jfrog rt u "hello.txt" "ramya-generic-local/demo/hello.txt"
