name: Build and Upload to Artifactory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up JDK 11 (Java example)
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      # Cache Gradle dependencies
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Build the project with Gradle
      - name: Build project
        run: ./gradlew build

      # Set up JFrog CLI
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v1
        with:
          version: '2.10.1'

      # Configure JFrog CLI with Artifactory API Key
      - name: Configure JFrog CLI
        run: |
          jfrog rt config --url https://artifactory.example.com/artifactory \
                          --apikey ${{ secrets.ARTIFACTORY_API_KEY }} \
                          --interactive=false

      # Upload build artifacts to Artifactory
      - name: Upload artifacts
        run: |
          jfrog rt u "build/libs/*.jar" "libs-release-local/java/com/example/" --build-name="my-build" --build-number="${{ github.run_id }}"

      # Collect build info
      - name: Collect build info
        run: |
          jfrog rt bce "my-build" "${{ github.run_id }}"

      # Publish build info to Artifactory
      - name: Publish build info to Artifactory
        run: |
          jfrog rt bp "my-build" "${{ github.run_id }}"
